name: Blmrs
favicon: null
layout_spectrum: 0.9355832193978131
typography_spectrum: 0.8492802097462118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.038841432658955455
  lightness: 0.8435089502017945
  saturation: 0.39339821226894855
  rhythmicContrast: 0.5929392147809267
purpose: []
